// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzlcfzkwdmwxllgvlete.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bGNmemt3ZG13eGxsZ3ZsZXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MjY0MjYsImV4cCI6MjA1NzQwMjQyNn0.SQJLxr5g2TnTs8qFb5gIaf-h0QyXUsYi1u-WIfjDu6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);